name = input('What is your name? ')
print('UGH,I HATE YOU, ' + name.upper() + '!')
color = input('What is your favorite color? ')
print('UGH, ' 'I HATE ' + color.upper() + '. ' 'THERE ARE SO MANY BETTER COLORS.')
subject = input('What is your favorite subject in school? ')
print('UGH, I HATE '  + subject.upper() + '.')
swear = input('What is your favorite swear word? ')
print('OH SHIT! ' + swear.upper() + ' IS MY FAVORITE TOO!!' ' I STILL HATE YOU THOUGH, ' + name.upper() + '!')
print('UGH, I HATE EVERYTHING! BYE! BYE BYE!')